name: log_calico
description: Provides log filtering, buffering, and retry.
version: 1.0.0
homepage: https://github.com/miyakeryo/log_calico

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  localstorage: ^4.0.0+1
  synchronized: ^3.0.1
  collection: ^1.16.0
  meta: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
