name: log_calico
description: Provides log filtering, buffering, and retry.
version: 1.3.1
homepage: https://github.com/miyakeryo/log_calico

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  localstorage: ^4.0.1+2
  synchronized: ^3.1.0
  collection: ^1.17.0
  meta: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
